SELECT * FROM "tblArtifact_Master" am
  LEFT JOIN "BC Artifact Inventory" j1 on j1."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblAllBangles" j2 on j2."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblBeads" j4 on j4."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblBells" j5 on j5."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblBuddhas" j6 on j6."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblCrucibles" j7 on j7."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblCylinders" j8 on j8."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblDiscs" j9 on j9."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblElem" j10 on j10."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblFigurines" j11 on j11."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblGlassAnalyses" j12 on j12."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblIronArt" j13 on j13."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  -- LEFT JOIN "tblLIAdata,MMAP_Artifact_ID,3,text,YES
  LEFT JOIN "tblMetAnalysis_all" j15 on j15."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetElem" j16 on j16."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  -- LEFT JOIN "tblMetElem,tblelemental-Cu_MMAP_Artifact_ID,14,text,YES
  LEFT JOIN "tblMetElemHardness" j18 on j18."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  -- LEFT JOIN "tblMetElemHardness,tblelemental-Cu_MMAP_Artifact_ID,14,text,YES
  LEFT JOIN "tblMetHardness" j20 on j20."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetalAdze" j21 on j21."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetalAmorph" j22 on j22."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetalBlades" j23 on j23."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetalMisc" j24 on j24."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetalPoints" j25 on j25."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetalWire_Rod" j26 on j26."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMetal_Flat" j27 on j27."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMiscArt" j28 on j28."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMiscClay" j29 on j29."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblMiscStone" j30 on j30."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPMs" j31 on j31."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPellets" j32 on j32."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPestles" j33 on j33."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPipes" j34 on j34."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPotLocationsSmall" j35 on j35."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPotsNew" j36 on j36."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPrehistoric_Metal" j37 on j37."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblPrills" j38 on j38."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  -- LEFT JOIN "tblRaymaekerStoneAdzes,MMAP_Artifact_ID,3,text,YES
  LEFT JOIN "tblSherds" j40 on j40."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblSlagPrehist" j41 on j41."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblSpindleWhorls" j42 on j42."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblSpoons" j43 on j43."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblStoneADZE_BCorig" j44 on j44."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblStoneAdzesMMAPorig" j45 on j45."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblStoneAdzesNew" j46 on j46."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblStone_Cores" j47 on j47."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblStone_CoresOld" j48 on j48."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblStone_Flakes" j49 on j49."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblWorkedBone" j50 on j50."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblelemental-Cu" j51 on j51."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
  LEFT JOIN "tblmetallography" j52 on j52."MMAP_Artifact_ID" = am."MMAP_Artifact_ID"
;
