SELECT am.*,
  j7."Scond",
  j7."Trtmt",
  j7."MidDia",
  j7."EndDia",
  j7."Profile",
  j7."PerfDia",
  j7."PerfOrientation",
  j7."Design_Depth",
  j7."Newclass",
  j7."Type",
  j7."Oldclass",
  j7."Band_No",
  j7."BandsinDesign",
  j7."PigmentFace",
  j7."Amt_PigmentFace",
  j7."Distrib_PigmentFace",
  j7."PigmentSides",
  j7."Amt_PigmentSides",
  j7."Distrib_PigmentSides",
  j7."PigmentBody",
  j7."Amt_PigmentBody",
  j7."Distrib_PigmentBody",
  j7."PigmentEnds",
  j7."Amt_PigmentEnds",
  j7."Distrib_PigmentEnds",
  j7."PigmentPerf",
  j7."Amt_PigmentPerf",
  j7."Distrib_PigmentPerf",
  j7."Face_Stri",
  j7."Side_Stri",
  j7."Body_Stri",
  j7."End_stri",
  j7."Perf_Stri",
  j7."EndA Cond",
  j7."EndB Cond",
  j7."EndA_Shape",
  j7."EndA_Flare",
  j7."EndA_Damage",
  j7."EndB_Shape",
  j7."EndB_Flare",
  j7."EndB_Damage"
FROM "tblArtifact_Master" am

JOIN "tblCylinders" j7 ON j7."MMAP_Artifact_ID" = am."MMAP_Artifact_ID";
