SELECT am.*,
  j6."VernonNo",
  j6."Description",
  j6."Metal_Working",
  j6."Length",
  j6."Width",
  j6."Thickness",
  j6."OrigLen",
  j6."OrigWid",
  j6."OrigHt",
  j6."IntDepth",
  j6."BottomThick",
  j6."TotVol_ml",
  j6."MaxMetCap_gm",
  j6."EffMetCap_gm",
  j6."VernonWt",
  j6."PartsPresent",
  j6."RimShape",
  j6."Vitrif",
  j6."Lagging",
  j6."RedStain",
  j6."RedStainLoc",
  j6."RedStainHue",
  j6."RedStainExtent",
  j6."RedStainComment",
  j6."NoUses",
  j6."Temper",
  j6."Dross",
  j6."Slag_Glass",
  j6."Prills",
  j6."AnalysisComment",
  j6."Comment"
FROM "tblArtifact_Master" am

JOIN "tblCrucibles" j6 ON j6."MMAP_Artifact_ID" = am."MMAP_Artifact_ID";
