SELECT am.*,
  j10."SF Class",
  j10."Scond",
  j10."MaxHgt",
  j10."MaxLen",
  j10."MaxWid",
  j10."HornBaseDia",
  j10."CornCurvDia",
  j10."Hardness",
  j10."AnimalID",
  j10."Head",
  j10."Nose",
  j10."Horn",
  j10."Horn_Angle",
  j10."Hump",
  j10."Hump_Size",
  j10."Back",
  j10."Back_Slope",
  j10."ForeQ",
  j10."ForeQ_Size",
  j10."HindQ",
  j10."HindQ_Size",
  j10."Body",
  j10."Body_Size",
  j10."Body_XSection",
  j10."BodyLengthShape",
  j10."ForeLeg",
  j10."FLeg_Shape",
  j10."FLeg_Length",
  j10."HindLeg",
  j10."HLeg_Shape",
  j10."HLeg_Length",
  j10."Tail",
  j10."Defacing"
FROM "tblArtifact_Master" am

JOIN "tblFigurines" j10 ON j10."MMAP_Artifact_ID" = am."MMAP_Artifact_ID";
