SELECT am.*,
  j29."Scond",
  j29."TotlLen",
  j29."HandlLen",
  j29."HandlDia",
  j29."BaseHgt",
  j29."BaseDia",
  j29."BaseCurvLen",
  j29."HandlComplete",
  j29."BaseComplete",
  j29."HandlEndForm",
  j29."BaseShape",
  j29."Handle_Comm",
  j29."Base_Comm",
  j29."MunsCodePrim",
  j29."MunsColorPrim",
  j29."MunsCodeSec",
  j29."MunsColorSec",
  j29."ColorComm",
  j29."SurfAttr",
  j29."SurfAttrComm",
  j29."Concret",
  j29."ConcretComm",
  j29."FireCl",
  j29."FireClComm"
FROM "tblArtifact_Master" am

JOIN "tblPestles" j29 ON j29."MMAP_Artifact_ID" = am."MMAP_Artifact_ID";
