SELECT am.*,
  j31."Characteristic",
  j31."None_Obs",
  j31."Entire_Int",
  j31."Entire_Ext",
  j31."Rim_Top",
  j31."Inn_Rim",
  j31."Out_Rim",
  j31."Rim_Neck",
  j31."Neck",
  j31."Rim_Body",
  j31."Neck_Body",
  j31."In_UpBody",
  j31."Out_UpBody",
  j31."Midbody",
  j31."In_LoBody",
  j31."Out_LoBody",
  j31."In_Bot",
  j31."Out_Bot",
  j31."Foot_Bod",
  j31."In_Foot",
  j31."Out_Foot",
  j31."In_Neck",
  j31."Out_Neck",
  j31."Foot_Bot"
FROM "tblArtifact_Master" am

JOIN "tblPotLocationsSmall" j31 ON j31."MMAP_Artifact_ID" = am."MMAP_Artifact_ID";
