SELECT am.*,
  j39."SCond",
  j39."Color",
  j39."Texture",
  j39."StoneType",
  j39."Intact_Length",
  j39."Width",
  j39."BladeChordLen",
  j39."EdgeLen",
  j39."TangLength",
  j39."TangWidNeck",
  j39."ShoulderWidth",
  j39."PollTopWidth",
  j39."PollThickness",
  j39."EdgeChordHt",
  j39."MaxThickness",
  j39."MaxThickLoc",
  j39."EdgeAngle",
  j39."BkBevelLen",
  j39."DuffType",
  j39."BoerMahType",
  j39."MMAPtype",
  j39."Tang_Shoulder",
  j39."ShaftSideConverg",
  j39."ShaftXsection",
  j39."LongXsection",
  j39."EdgeShape",
  j39."PollShape",
  j39."BevelsBk_Face",
  j39."BevelsFace2",
  j39."BevelDef",
  j39."NeckShouldConfig",
  j39."TangXsection",
  j39."Intactness",
  j39."FragType",
  j39."FlakeScarsEdge",
  j39."FlakeScarsPoll",
  j39."FlakeScarsSides",
  j39."FlakeScarsPolished",
  j39."OtherFlakeScars",
  j39."DamageNotes",
  j39."DataSource"
FROM "tblArtifact_Master" am

JOIN "tblStoneAdzesNew" j39 ON j39."MMAP_Artifact_ID" = am."MMAP_Artifact_ID";
