    ('Column', 'column'),
    ('Id', 'id'),
    ('Mmap Artifact Id', 'mmap_artifact_id_s'),
    ('Site Name', 'site_name_s'),
    ('Date Discovered', 'date_discovered_s'),
    ('Bag Id', 'bag_id_s'),
    ('Artifact Condition', 'artifact_condition_s'),
    ('Artifact Class', 'artifact_class_s'),
    ('Maximum Dimension', 'maximum_dimension_s'),
    ('Weight', 'weight_s'),
    ('Count', 'count_s'),
    ('Burial No', 'burial_no_s'),
    ('Period', 'period_s'),
    ('Material', 'material_s'),
    ('Comments', 'comments_s'),
    ('Bur Phase', 'bur_phase_s'),
    ('Level', 'level_s'),
    ('Depcontext', 'depcontext_s'),
    ('Square', 'square_s'),
    ('Quad', 'quad_s'),
    ('Layer', 'layer_s'),
    ('Feano', 'feano_s'),
    ('Featype', 'featype_s'),
    ('Burassoc', 'burassoc_s'),
    ('Blocation', 'blocation_s'),
    ('Bodypart', 'bodypart_s'),
    ('Sherdample? S', 'sherd_sample?_s'),
    ('Sherdamp Location S', 'sherd_samp_location_s'),
    ('Thinection S', 'thin_section_s'),
    ('Ts Location', 'ts_location_s'),
    ('Ts No', 'ts_no_s'),
    ('Metample S', 'met_sample_s'),
    ('Metamp Loc S', 'met_samp_loc_s'),
    ('Sample Comment', 'sample_comment_s'),
    ('Artloc', 'artloc_s'),
    ('Conserved', 'conserved_s'),
    ('Glassample S', 'glass_sample_s'),
    ('Glamp S', 'gl_samp_s'),
    ('Gl Tech', 'gl_tech_s'),
    ('Gl Analy Date', 'gl_analy_date_s'),
    ('Entered By', 'entered_by_s'),
    ('Initial Date', 'initial_date_s'),
    ('Date Last Modified', 'date_last_modified_s'),
    ('Txtimagename1', 'txtimagename1_s'),
    ('Txtimagename2', 'txtimagename2_s'),
    ('Txtimagename3', 'txtimagename3_s'),
    ('Txtimagename4', 'txtimagename4_s'),
    ('Txtimagename5', 'txtimagename5_s'),
    ('Txtdrawingname', 'txtdrawingname_s'),
    ('Flag For Check', 'flag_for_check'),
